### ISSUE TITLE
Error: There can be only one type named "CloudinaryImageFormat" when used with regular CloudinaryImage

### ISSUE THREAD

**Issue by Bravo555** [Globobeet/keystone-cloudinary-gallery-field#1]
Code:
```js
const { CloudinaryImage } = require("@keystonejs/fields");
const { CloudinaryAdapter } = require("@keystonejs/file-adapters");
const KeystoneCloudinaryGallery = require('@globobeet/keystone-cloudinary-gallery-field');

// ...

keystone.createList('Item', {
  fields: {
    heroImage: { type: CloudinaryImage, adapter: cloudinaryAdapter },
    imageGallery: { type: KeystoneCloudinaryGallery, adapter: cloudinaryAdapter }
  }
});
```
I get the error:
```
✖ Initialising Keystone instance
Error: There can be only one type named "CloudinaryImageFormat".

Field "CloudinaryImageFormat.prettyName" can only be defined once.

Field "CloudinaryImageFormat.width" can only be defined once.

Field "CloudinaryImageFormat.height" can only be defined once.

Field "CloudinaryImageFormat.crop" can only be defined once.

Field "CloudinaryImageFormat.aspect_ratio" can only be defined once.

Field "CloudinaryImageFormat.gravity" can only be defined once.

Field "CloudinaryImageFormat.zoom" can only be defined once.

Field "CloudinaryImageFormat.x" can only be defined once.

Field "CloudinaryImageFormat.y" can only be defined once.

Field "CloudinaryImageFormat.format" can only be defined once.

Field "CloudinaryImageFormat.fetch_format" can only be defined once.

Field "CloudinaryImageFormat.quality" can only be defined once.

Field "CloudinaryImageFormat.radius" can only be defined once.

Field "CloudinaryImageFormat.angle" can only be defined once.

Field "CloudinaryImageFormat.effect" can only be defined once.

Field "CloudinaryImageFormat.opacity" can only be defined once.

Field "CloudinaryImageFormat.border" can only be defined once.

Field "CloudinaryImageFormat.background" can only be defined once.

Field "CloudinaryImageFormat.overlay" can only be defined once.

Field "CloudinaryImageFormat.underlay" can only be defined once.

Field "CloudinaryImageFormat.default_image" can only be defined once.

Field "CloudinaryImageFormat.delay" can only be defined once.

Field "CloudinaryImageFormat.color" can only be defined once.

Field "CloudinaryImageFormat.color_space" can only be defined once.

Field "CloudinaryImageFormat.dpr" can only be defined once.

Field "CloudinaryImageFormat.page" can only be defined once.

Field "CloudinaryImageFormat.density" can only be defined once.

Field "CloudinaryImageFormat.flags" can only be defined once.

Field "CloudinaryImageFormat.transformation" can only be defined once.
    at assertValidSDL (/home/marcel/Documents/dev/projects/apartments-website/node_modules/graphql/validation/validate.js:108:11)
    at Object.buildASTSchema (/home/marcel/Documents/dev/projects/apartments-website/node_modules/graphql/utilities/buildASTSchema.js:71:34)
    at Object.buildSchemaFromTypeDefinitions (/home/marcel/Documents/dev/projects/apartments-website/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:25:28)
    at Object.makeExecutableSchema (/home/marcel/Documents/dev/projects/apartments-website/node_modules/graphql-tools/dist/makeExecutableSchema.js:26:29)
    at ApolloServer.initSchema (/home/marcel/Documents/dev/projects/apartments-website/node_modules/apollo-server-core/dist/ApolloServer.js:272:49)
    at new ApolloServerBase (/home/marcel/Documents/dev/projects/apartments-website/node_modules/apollo-server-core/dist/ApolloServer.js:194:30)
    at new ApolloServer (/home/marcel/Documents/dev/projects/apartments-website/node_modules/apollo-server-express/dist/ApolloServer.js:60:9)
    at createApolloServer (/home/marcel/Documents/dev/projects/apartments-website/node_modules/@keystonejs/app-graphql/lib/apolloServer.js:144:18)
    at GraphQLApp.prepareMiddleware (/home/marcel/Documents/dev/projects/apartments-website/node_modules/@keystonejs/app-graphql/index.js:23:20)
    at /home/marcel/Documents/dev/projects/apartments-website/node_modules/@keystonejs/keystone/lib/Keystone/index.js:702:17
    at Array.map (<anonymous>)
    at Keystone._prepareMiddlewares (/home/marcel/Documents/dev/projects/apartments-website/node_modules/@keystonejs/keystone/lib/Keystone/index.js:701:12)
    at Keystone.prepare (/home/marcel/Documents/dev/projects/apartments-website/node_modules/@keystonejs/keystone/lib/Keystone/index.js:719:36)
    at executeDefaultServer (/home/marcel/Documents/dev/projects/apartments-website/node_modules/@keystonejs/keystone/bin/utils.js:149:42)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @keystonejs/example-projects-starter@5.0.2 dev: `cross-env NODE_ENV=development DISABLE_LOGGING=true keystone dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @keystonejs/example-projects-starter@5.0.2 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/marcel/.npm/_logs/2020-07-22T17_28_37_329Z-debug.log
```

**Comment by Bravo555** [comment]
Do you have any suspicions as to what might be causing the issue and what would be the best course of action to fix it? I tried looking into the code but I haven't managed to find anything, as I'm not versed with graphql.
Thanks

**Comment by adriancbo** [comment]
@Bravo555 updating `@keystonejs/fields` fixed this for me.

**Comment by Bravo555** [comment]
@adriancbo thanks for the suggestion! I updated `@keystonejs/fields` to `14.0.0` but I still have the issue. Could it be because the dependencies still require old, buggy versions? Here's the `npm ls @keystonejs/fields` output:
```
➤ npm ls @keystonejs/fields
@keystonejs/example-projects-starter@5.0.2 /home/marcel/Documents/dev/projects/apartments-website
├─┬ @globobeet/keystone-cloudinary-gallery-field@1.0.3
│ ├─┬ @keystonejs/adapter-knex@9.0.1
│ │ ├─┬ @keystonejs/fields-auto-increment@5.1.11
│ │ │ └── @keystonejs/fields@14.0.0  deduped
│ │ └─┬ @keystonejs/keystone@8.1.4
│ │   └─┬ @keystonejs/fields@9.0.5 
│ │     ├─┬ @keystonejs/adapter-mongoose@8.1.3
│ │     │ └─┬ @keystonejs/keystone@11.2.0
│ │     │   └─┬ @keystonejs/fields@13.0.2 
│ │     │     ├─┬ @keystonejs/app-admin-ui@7.1.0
│ │     │     │ └─┬ @keystonejs/fields@14.0.0 
│ │     │     │   └─┬ @keystonejs/adapter-knex@11.0.0
│ │     │     │     └─┬ @keystonejs/keystone@12.0.0
│ │     │     │       └── @keystonejs/fields@14.0.0  deduped
│ │     │     └─┬ @keystonejs/field-content@7.0.2
│ │     │       └─┬ @keystonejs/fields@14.0.0 
│ │     │         └─┬ @keystonejs/adapter-knex@11.0.0
│ │     │           └─┬ @keystonejs/keystone@12.0.0
│ │     │             └── @keystonejs/fields@14.0.0  deduped
│ │     ├─┬ @keystonejs/app-admin-ui@5.12.0
│ │     │ └── @keystonejs/fields@9.0.5  deduped
│ │     └─┬ @keystonejs/field-content@5.4.8
│ │       └── @keystonejs/fields@9.0.5  deduped
│ ├─┬ @keystonejs/adapter-mongoose@8.0.1
│ │ ├─┬ @keystonejs/fields-mongoid@5.1.10
│ │ │ ├─┬ @keystonejs/adapter-knex@10.1.0
│ │ │ │ └─┬ @keystonejs/keystone@11.2.0
│ │ │ │   └── @keystonejs/fields@13.0.2 
│ │ │ └─┬ @keystonejs/fields@11.0.0 
│ │ │   ├─┬ @keystonejs/app-admin-ui@6.0.2
│ │ │   │ └── @keystonejs/fields@11.0.0  deduped
│ │ │   └─┬ @keystonejs/field-content@6.0.1
│ │ │     └── @keystonejs/fields@11.0.0  deduped
│ │ └─┬ @keystonejs/keystone@8.1.4
│ │   └─┬ @keystonejs/fields@9.0.5 
│ │     ├─┬ @keystonejs/adapter-mongoose@8.1.3
│ │     │ ├─┬ @keystonejs/fields-mongoid@6.0.2
│ │     │ │ ├─┬ @keystonejs/adapter-knex@11.0.0
│ │     │ │ │ └─┬ @keystonejs/keystone@12.0.0
│ │     │ │ │   └── @keystonejs/fields@14.0.0  deduped
│ │     │ │ └─┬ @keystonejs/fields@14.0.0 
│ │     │ │   ├─┬ @keystonejs/app-admin-ui@7.1.0
│ │     │ │   │ └── @keystonejs/fields@14.0.0  deduped
│ │     │ │   └─┬ @keystonejs/field-content@7.0.2
│ │     │ │     └── @keystonejs/fields@14.0.0  deduped
│ │     │ └─┬ @keystonejs/keystone@11.2.0
│ │     │   └─┬ @keystonejs/fields@13.0.2 
│ │     │     ├─┬ @keystonejs/app-admin-ui@7.1.0
│ │     │     │ └─┬ @keystonejs/fields@14.0.0 
│ │     │     │   └─┬ @keystonejs/adapter-knex@11.0.0
│ │     │     │     └─┬ @keystonejs/keystone@12.0.0
│ │     │     │       └── @keystonejs/fields@14.0.0  deduped
│ │     │     └─┬ @keystonejs/field-content@7.0.2
│ │     │       └─┬ @keystonejs/fields@14.0.0 
│ │     │         └─┬ @keystonejs/adapter-knex@11.0.0
│ │     │           └─┬ @keystonejs/keystone@12.0.0
│ │     │             └── @keystonejs/fields@14.0.0  deduped
│ │     ├─┬ @keystonejs/app-admin-ui@5.12.0
│ │     │ └── @keystonejs/fields@9.0.5  deduped
│ │     └─┬ @keystonejs/field-content@5.4.8
│ │       └── @keystonejs/fields@9.0.5  deduped
│ └─┬ @keystonejs/fields@9.0.0 
│   ├─┬ @keystonejs/app-admin-ui@5.12.0
│   │ └── UNMET DEPENDENCY @keystonejs/fields@^9.0.5
│   ├─┬ @keystonejs/field-content@5.4.8
│   │ └─┬ @keystonejs/fields@9.0.5 
│   │   └─┬ @keystonejs/adapter-mongoose@8.1.3
│   │     ├─┬ @keystonejs/fields-mongoid@6.0.2
│   │     │ ├─┬ @keystonejs/adapter-knex@11.0.0
│   │     │ │ └─┬ @keystonejs/keystone@12.0.0
│   │     │ │   └── @keystonejs/fields@14.0.0  deduped
│   │     │ └─┬ @keystonejs/fields@14.0.0 
│   │     │   ├─┬ @keystonejs/app-admin-ui@7.1.0
│   │     │   │ └── @keystonejs/fields@14.0.0  deduped
│   │     │   └─┬ @keystonejs/field-content@7.0.2
│   │     │     └── @keystonejs/fields@14.0.0  deduped
│   │     └─┬ @keystonejs/keystone@11.2.0
│   │       └─┬ @keystonejs/fields@13.0.2 
│   │         ├─┬ @keystonejs/app-admin-ui@7.1.0
│   │         │ └─┬ @keystonejs/fields@14.0.0 
│   │         │   └─┬ @keystonejs/adapter-knex@11.0.0
│   │         │     └─┬ @keystonejs/keystone@12.0.0
│   │         │       └── @keystonejs/fields@14.0.0  deduped
│   │         └─┬ @keystonejs/field-content@7.0.2
│   │           └─┬ @keystonejs/fields@14.0.0 
│   │             └─┬ @keystonejs/adapter-knex@11.0.0
│   │               └─┬ @keystonejs/keystone@12.0.0
│   │                 └── @keystonejs/fields@14.0.0  deduped
│   ├── @keystonejs/fields@9.0.5  extraneous
│   └─┬ @keystonejs/test-utils@6.2.0
│     └─┬ @keystonejs/keystone@11.2.0
│       └── @keystonejs/fields@13.0.2 
├─┬ @keystonejs/adapter-mongoose@9.0.0
│ └─┬ @keystonejs/fields-mongoid@6.0.2
│   └── @keystonejs/fields@14.0.0  deduped
├─┬ @keystonejs/app-admin-ui@7.1.0
│ └── @keystonejs/fields@14.0.0  deduped
├─┬ @keystonejs/auth-password@5.1.11
│ └── @keystonejs/fields@14.0.0  deduped
├─┬ @keystonejs/fields@14.0.0 
│ └─┬ @keystonejs/field-content@7.0.2
│   └── @keystonejs/fields@14.0.0  deduped
├─┬ @keystonejs/fields-markdown@5.2.2
│ └── @keystonejs/fields@14.0.0  deduped
└─┬ @keystonejs/keystone@12.0.0
  └── @keystonejs/fields@14.0.0  deduped

npm ERR! extraneous: @keystonejs/fields@9.0.5 /home/marcel/Documents/dev/projects/apartments-website/node_modules/@globobeet/keystone-cloudinary-gallery-field/node_modules/@keystonejs/fields/node_modules/@keystonejs/fields
npm ERR! missing: @keystonejs/fields@^9.0.5, required by @keystonejs/app-admin-ui@5.12.0
```
It still requires old versions, despite deleting both `node_modules/` and `package-lock.json` and installing deps from scratch. Is there a way to fix this?

**Comment by adriancbo** [comment]
i cloned this repo into a directory outside of my keystone project, and linked the package locally. here's what i did:
1. clone this repo and update `@keystonejs/fields` to `14.0.0` and `@keystonejs/build-field-types` to `5.2.10` in package.json
2. remove the lock file and run `yarn install`
3. in the root of this extension, run `yarn link`
4. in the root of your main project, run `yarn link @globobeet/keystone-cloudinary-gallery-field`

**Comment by adriancbo** [comment]
i'll submit a PR if i have time later, but since moved on to a different CMS.

**Comment by Bravo555** [comment]
Thanks for the response and help! And I have one more question, what CMS have you moved to? I'd like to take a look at it as well.

**Comment by joshlasdin** [comment]
Just published an update that should address this issue -- something was going on with newer versions of Keystone. @Bravo555 Let me know if you continue to have issues!

**Comment by Bravo555** [comment]
Thanks for the update! Unfortunately still no luck.
```
✖ Initialising Keystone instance
TypeError: Cannot read property 'create' of undefined
    at /home/marcel/Documents/dev/projects/apartments-website/node_modules/@keystonejs/keystone/lib/ListTypes/list.js:255:48
    at Array.filter (<anonymous>)
    at List.getFieldsWithAccess (/home/marcel/Documents/dev/projects/apartments-website/node_modules/@keystonejs/keystone/lib/ListTypes/list.js:255:8)
    at List.getGqlMutations (/home/marcel/Documents/dev/projects/apartments-website/node_modules/@keystonejs/keystone/lib/ListTypes/list.js:1089:31)
    at /home/marcel/Documents/dev/projects/apartments-website/node_modules/@keystonejs/keystone/lib/providers/listCRUD.js:35:53
    at Array.map (<anonymous>)
    at ListCRUDProvider.getMutations (/home/marcel/Documents/dev/projects/apartments-website/node_modules/@keystonejs/keystone/lib/providers/listCRUD.js:35:36)
    at /home/marcel/Documents/dev/projects/apartments-website/node_modules/@keystonejs/keystone/lib/Keystone/index.js:516:65
    at Array.map (<anonymous>)
    at Keystone.getTypeDefs (/home/marcel/Documents/dev/projects/apartments-website/node_modules/@keystonejs/keystone/lib/Keystone/index.js:516:54)
    at Keystone.createApolloServer (/home/marcel/Documents/dev/projects/apartments-website/node_modules/@keystonejs/keystone/lib/Keystone/index.js:445:22)
    at Keystone.prepare (/home/marcel/Documents/dev/projects/apartments-website/node_modules/@keystonejs/keystone/lib/Keystone/index.js:605:10)
    at executeDefaultServer (/home/marcel/Documents/dev/projects/apartments-website/node_modules/@keystonejs/keystone/bin/utils.js:149:42)
```

**Comment by joshlasdin** [comment]
@Bravo555 are you able to set up a demo on CodePen or something like that to reproduce?

**Comment by Bravo555** [comment]
Aw whoops, I forgot to actually update the dependency :facepalm: I updated and everything works, thank you for the fix! :)

**Comment by joshlasdin** [comment]
hahaha, glad it's working!
